# Generated by Django 4.2.7 on 2023-12-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
