# Generated by Django 4.2.7 on 2023-12-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
