# Generated by Django 4.2.8 on 2023-12-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0002_documenttable_tablerow_rowcell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subheading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(default='', max_length=255)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.heading')),
            ],
        ),
    ]
