# Generated by Django 4.2.8 on 2023-12-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0002_documenttable_tablerow_rowcell'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('content', models.TextField()),
                ('document_paragraph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.documentparagraph')),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.userdocument')),
            ],
        ),
    ]
