# Generated by Django 4.2.7 on 2023-12-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0002_remove_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='provider',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
