# Generated by Django 5.0 on 2023-12-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0003_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.userdocument')),
            ],
        ),
    ]
