# Generated by Django 4.2.8 on 2024-01-03 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0003_subheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(default='default_user', on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.user'),
            preserve_default=False,
        ),
    ]
