# Generated by Django 4.2.7 on 2023-12-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0004_userprofile_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
