# Generated by Django 5.0 on 2023-12-24 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0004_endnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListParagraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('document_paragraph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.documentparagraph')),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.userdocument')),
            ],
        ),
    ]
