# Generated by Django 4.2.8 on 2024-01-06 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0004_userdocument_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentParagraphResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('original_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.documentparagraph')),
            ],
        ),
    ]
