# Generated by Django 4.2.7 on 2023-12-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0005_listparagraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.userdocument')),
            ],
        ),
    ]
