# Generated by Django 4.2.7 on 2023-12-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeet2582_backend', '0007_tablerow'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowCell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('document_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.documenttable')),
                ('table_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.tablerow')),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeet2582_backend.userdocument')),
            ],
        ),
    ]
